[package]
name = "asterizm"
version = "1.0.0"
authors = []

[addresses]
asterizm = "0xcf097facd876f46de13c8a2400a1f918d2bf358f42c983ef9124de16cdca7478"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
